mailit-after/config/routes.rb
Mailit::Application.routes.draw do
  root to: 'newsletters#index'
  resources :newsletters do
    member { post :deliver }
  end
  match "/delayed_job" => DelayedJobWeb, anchor: false
end

mailit-after/app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  def self.deliver(id)
    find(id).deliver
  end
  
  def deliver
    sleep 10 # simulate long newsletter delivery
    update_attribute(:delivered_at, Time.zone.now)
  end
end

mailit-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

mailit-after/app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  def deliver
    Newsletter.delay(queue: "newsletter", priority: 20, run_at: 5.minutes.from_now).deliver(params[:id])
    redirect_to newsletters_url, notice: "Delivering newsletter."
  end

  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.find(params[:id])
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      redirect_to @newsletter, notice: "Successfully created newsletter."
    else
      render :new
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(params[:newsletter])
      redirect_to @newsletter, notice: "Successfully updated newsletter."
    else
      render :edit
    end
  end

  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy
    redirect_to newsletters_url, notice: "Successfully destroyed newsletter."
  end
end

mailit-after/app/helpers/application_helper.rb
module ApplicationHelper
end

mailit-after/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

mailit-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsletters</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
      <div class="clear"></div>
    </div>
  </body>
</html>

mailit-after/app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>
      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mailit-after/app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

mailit-after/app/views/newsletters/index.html.erb
<h1>Newsletters</h1>

<% @newsletters.each do |newsletter| %>
  <div class="newsletter">
    <h2><%= newsletter.subject %></h2>
    <% if newsletter.delivered_at.present? %>
      Delivered on <%= newsletter.delivered_at.strftime("%B %d, %Y at %I:%M:%S") %><br />
    <% end %>
    <%= link_to "View", newsletter %> |
    <%= link_to "Deliver", deliver_newsletter_path(newsletter), method: :post %>
  </div>
<% end %>

<p><%= link_to "New Newsletter", new_newsletter_path %></p>

mailit-after/app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

mailit-after/app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @newsletter.subject %>
</p>

<p>
  <b>Delivered at:</b>
  <%= @newsletter.delivered_at %>
</p>


<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>